// Regenerates node_exports_gen.go: every named export of every Node
// builtin module, as reported by the real Node running this script.
// Run from internal/host with `go generate` (see node_exports.go).
import { builtinModules } from "node:module";
import { writeFileSync } from "node:fs";

process.removeAllListeners("warning");
process.on("warning", () => {});

const lines = [];
for (const m of [...builtinModules].sort()) {
  if (m.startsWith("_")) continue;
  const spec = m.startsWith("node:") ? m : "node:" + m;
  const ns = await import(spec);
  const names = Object.keys(ns)
    .filter((k) => k !== "default")
    .sort()
    .map((k) => (typeof ns[k] === "function" ? k + "()" : k));
  lines.push(`\t${JSON.stringify(m.replace(/^node:/, ""))}: ${JSON.stringify(names.join(" "))},`);
}

writeFileSync(
  "node_exports_gen.go",
  `// Code generated by gen_node_exports.mjs from Node ${process.version}; DO NOT EDIT.

package host

// nodeBuiltinExports lists each Node builtin's named exports, space-
// separated; a trailing "()" marks a function (or class).
var nodeBuiltinExports = map[string]string{
${lines.join("\n")}
}
`,
);
